/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_andiwand_packetsocket_EthernetSocket */

#ifndef _Included_at_andiwand_packetsocket_EthernetSocket
#define _Included_at_andiwand_packetsocket_EthernetSocket
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    openImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_at_andiwand_packetsocket_EthernetSocket_openImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_andiwand_packetsocket_EthernetSocket_closeImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    bindImpl
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_andiwand_packetsocket_EthernetSocket_bindImpl
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    enablePromiscMode
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_andiwand_packetsocket_EthernetSocket_enablePromiscModeImpl
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    receiveImpl
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_at_andiwand_packetsocket_EthernetSocket_receiveImpl
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    receiveFromImpl
 * Signature: (ILjava/lang/String;[BIII)I
 */
JNIEXPORT jint JNICALL Java_at_andiwand_packetsocket_EthernetSocket_receiveFromImpl
  (JNIEnv *, jclass, jint, jstring, jbyteArray, jint, jint, jint);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    sendImpl
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_at_andiwand_packetsocket_EthernetSocket_sendImpl
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     at_andiwand_packetsocket_EthernetSocket
 * Method:    sendToImpl
 * Signature: (ILjava/lang/String;[BIII)I
 */
JNIEXPORT jint JNICALL Java_at_andiwand_packetsocket_EthernetSocket_sendToImpl
  (JNIEnv *, jclass, jint, jstring, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
